imports:
    - { resource: parameters.yml }
    - { resource: controllers.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         false
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
          datetime: MPWAR\Infrastructure\Doctrine\DBAL\DateTimeType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
              mappings:
                question_type:
                  type: yml
                  dir: %kernel.root_dir%/../src/MPWAR/Module/QuestionType/Infrastructure/Persistence
                  prefix: MPWAR\Module\QuestionType\Domain
                  is_bundle: false

sensio_framework_extra:
    view: { annotations: false }

fos_rest:
  format_listener:
    rules:
      - { path: ~, host: ~, fallback_format: json, prefer_extension: false }
  view:
    view_response_listener: force
  serializer:
    serialize_null: true

# jms_serializer:
#     visitors:
#         json:
#             options: JSON_PRETTY_PRINT
#     metadata:
#         directories:
#             question_type:
#                 namespace_prefix: "MPWAR\\Module\\QuestionType\\Contract\\Response"
#                 path: %kernel.root_dir%/Resources/serializer/question_type

parameters:
   jms_serializer.datetime_handler.class: MPWAR\Api\Infrastructure\JMSSerializer\DateTimeHandler
