services:

  mpwar.controller.question.get:
    class: MPWAR\Api\Controller\Question\QuestionGetController
    arguments:
      - @mysql

  mpwar.controller.question.post:
    class: MPWAR\Api\Controller\Question\QuestionPostController
    arguments:
      - @command_bus

  mpwar.controller.questiontype.get:
    class: MPWAR\Api\Controller\QuestionType\QuestionTypeGetController
    arguments:
      - @mysql

  mpwar.controller.questiontype.post:
    class: MPWAR\Api\Controller\QuestionType\QuestionTypePostController
    arguments:
      - @command_bus

  mpwar.controller.user.post:
    class: MPWAR\Api\Controller\User\UserPostController
    arguments:
      - @command_bus

  mpwar.controller.exam.get:
    class: MPWAR\Api\Controller\Exam\ExamGetController
    arguments:
      - @mysql

  mpwar.controller.exam.post:
    class: MPWAR\Api\Controller\Exam\ExamPostController
    arguments:
      - @command_bus